### ISSUE TITLE
Encode bitmessages as a key:value structure or json or msgpack

### ISSUE THREAD

**Issue by mofosyne** [mailchuck/PyBitmessage#112]
Current approach of subject and a body field is a bit limiting.

It would be good to consider using yaml, json, msgpack or some form of structure that would allow for easier future extensibility of the messages in future version.

Or at the very least, structure the packet as 

`[packet-type]` `[packet-version]` `[subject]` `[body]`

e.g. 

> yaml | v2 | this is a message header | { body : "hello world", hashtag : ["newmsg","dog"], parentmsg:{md5:"2342...",header:"I am parent", msg:"I am your father"}}

**Comment by PeterSurda** [comment]
The protocol can be extended to support this. The [message encoding](https://bitmessage.org/wiki/Protocol_specification#Message_Encodings) field was designed to indicate this. However, there is a comment there by Atheros to use 8bit encoding, which I think makes sense (MIME wastes about 33% of data due to base64 encoding). This problem would also apply to JSON and yaml, but msgpack seems to make sense. In addition, I think we should allow zlib compression.

Furthermore, we can use this to split long messages into multiple network objects. Each would still require a separate PoW, so that should mitigate spam.

**Comment by PeterSurda** [comment]
Extended encoding is now available in v0.6 of the official client for experimenting, can be adjusted for features.
