### ISSUE TITLE
What the bitmessage packet structure? Are we decrypting the entire message?

### ISSUE THREAD

**Issue by mofosyne** [mailchuck/PyBitmessage#125]
I think it would be nice if there is some wiki documentation about actual protocol format.

But anyway I was thinking. If you are decrypting the entire message. Does longer message take longer to decrypt?

If so, then could you improve scalability by creating a small field with a small fixed message (say 3 bytes saying "yes"), you can try checking your decryption against?

**Comment by mofosyne** [comment]
Ah, so that's the general structure, but the question about decrypting the entire message remains.

https://bitmessage.org/wiki/Protocol_specification

**Comment by PeterSurda** [comment]
I looked at the code and it looks like decrypting a longer mesage probably takes longer. It also looks like probably you can decode it in chunks, at least the example code for OpenSSL's EVP_CipherUpdate does use chunks, even though the code in PyBitmessage doesn't.

However, I suspect that EVP_CipherUpdate fails immediately rather than after processing the whole message, in other words, failing to decrypt a longer meassage probably does not take longer. So you cannot really improve decryption performance of failed decryption. However, you could reduce network bandwidth by having a "lightweight" node, see: https://github.com/mailchuck/PyBitmessage/issues/46
