### ISSUE TITLE
migration (from pybitmessage 0.4.4) wizard

### ISSUE THREAD

**Issue by mailchuck** [mailchuck/PyBitmessage#20]

**Comment by ghost** [comment]
What needs to be migrated? Shouldn't it just work automatically?

**Comment by PeterSurda** [comment]
I forgot why I originally had it. I probably imagined there would be some new stuff but either scrapped them or postponed. I tend to aggre, there is so far no change that wouldn't process automatically. The only reason I can think of why this may be helpful is to flag mailchuck.com user accounts as gateway accounts, but that can be done differently in my opinion. I'll close.

**Comment by PeterSurda** [comment]
Maybe it was migrating from official pybitmessage to mailchuck pybitmessage, which is now not necessary. Looking at my emails, I asked @Atheros if I could join the project on October 11th and if my recollection is correct, I wrote him immediately after I had the idea. The opening of this issue predates that, so that's probably it. Remains closed.
