### ISSUE TITLE
rebranding, rename repository

### ISSUE THREAD

**Issue by mailchuck** [mailchuck/PyBitmessage#31]
- in order not to confuse users, in particular Mailchuck users, rebrand
- suggested new name "MailChuckApp"

**Comment by ghost** [comment]
I also suggest renaming the application internally (filenames,binaries,etc), so it does not collide with existing PyBitmessage[upstream] installations when being compiled and installed.

**Comment by PeterSurda** [comment]
@krosos what about user data, should it reuse the ones from pybitmessage or use separate ones and just import on first launch? So far, both the sqlite3 database and keys.dat are compatible but that may change at some stage. And what if, for example, if I implement custom folders, these won't be visible in the original pybitmessage, even though I don't need to change the database layout.

**Comment by ghost** [comment]
Okay, if compatibility stops, what happens to the data, can there be an import pybitmessage to fork-of-pybitmessage function?

I was more looking into installing both programms at the same time to follow development (okay, this is doable without installing it, just running it).
I think I will solve this with an patch in an ebuild, so they don't conflict with each other.

**Comment by PeterSurda** [comment]
I haven't yet thought yet about what happens when compatibility breaks, rather merely noted that I need to make some decisions before I break compatibility. So far there isn't anything specific planned that would break it, the example with folders is the maximum incompatible extent that I can think of. That won't really break official pybitmessage, it will just cause the messages in those folders not be compatible.

If your focus is more narrow, just testing, there is no need to use ebuild. You can just check out my fork to any folder and run the app from there. There are no new python libraries needed and no need to install anything. There is an undocumented opencl functionality that can be turned on manually in the config file, but if opencl libraries are missing it will just cleanly skip over it.

**Comment by mailchuck** [comment]
Atheros agreed that we'll join our forces, see https://bitmessage.org/forum/index.php/topic,4812.0.html

So I'll merge the UI changes to the main pybitmessage and there is no need to rebrand.
