### ISSUE TITLE
Opencl

### ISSUE THREAD

**Issue by mailchuck** [mailchuck/PyBitmessage#37]
- [x] it now expects to choose device on commandline
- [ ] it appears broken on AMD

**Comment by PeterSurda** [comment]
Since e78c5820af072b4a08d389850cc0ceb80841d28d it autodetects all GPUs, no more need for commandline.

**Comment by PeterSurda** [comment]
Since 1fda2231afe080f5d855df8085f71a1a2acc7fe6 uses a different SWAP64 which works on my AMD.

The culprit is actually this part:

```
finalhash[0] = SWAP64(a + 0x6a09e667f3bcc908UL);
finalhash[1] = SWAP64(b + 0xbb67ae8584caa73bUL);
finalhash[2] = SWAP64(c + 0x3c6ef372fe94f82bUL);
finalhash[3] = SWAP64(d + 0xa54ff53a5f1d36f1UL);
finalhash[4] = SWAP64(e + 0x510e527fade682d1UL);
finalhash[5] = SWAP64(f + 0x9b05688c2b3e6c1fUL);
finalhash[6] = SWAP64(g + 0x1f83d9abfb41bd6bUL);
finalhash[7] = SWAP64(h + 0x5be0cd19137e2179UL);
```

and

```
return SWAP64(a + 0x6a09e667f3bcc908UL);
```

They don't seem to work on AMD.

The code will now test the result, and if it fails, it will disable OpenCL for the rest of the session and notify the user that OpenCL is broken and they should contact the developers.
